---
# tasks file for terraform
- name: Add Hashicorp GPG apt Key
  become: yes
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Hashicorp Repository
  become: yes
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com/ focal main"
    state: present

- name: Update apt and install terraform
  become: yes
  apt:
    name: terraform
    state: latest
    update_cache: true