---
# tasks file for requirements
- name: install ansible & required packages
  become: yes
  apt:
    pkg: 
    - ansible
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
    - python3
    - gnupg
    - lsb-release
    state: present
    update_cache: yes